Vagrant.configure("2") do |config|
  config.vm.box = "lxc-precise64"
  config.vm.box_url = "http://dl.dropbox.com/u/13510779/lxc-precise-amd64-2013-07-12.box"
  config.vm.provider :lxc
  
  config.vm.provision :puppet do |puppet|
  	puppet.module_path = "modules"
  	puppet.options = "--verbose --debug"
  end

  config.vm.synced_folder "../hubot", "/opt/hubot", nfs: true
end
