Vagrant.configure("2") do |config|
  config.vm.box = "lxc-raring64"
  config.vm.box_url = "http://bit.ly/vagrant-lxc-raring64-2013-07-12"
  config.vm.provider :lxc
  
  config.vm.provision :puppet do |puppet|
  	puppet.module_path = "modules"
  	puppet.options = "--templatedir /vagrant/templates --verbose --debug --http_proxy_host=10.0.3.1 --http_proxy_port=3128"
  end

  config.vm.synced_folder "../hubot", "/opt/hubot", nfs: true

  config.ssh.forward_agent = true
end
